### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [awkimball/akzsh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a LICENSE - if you haven't already decided on one,  I recommend [choosealicense.com](https://choosealicense.com).

**Comment by awkimball** [comment]
Fixed! Sorry for the delay.

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/657
